coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - docs/
  - .github/
  - .pre-commit-config.yaml
  - pyproject.toml
  - README.md
