# The `_version` module is auto-generated by setuptools_scm at install time.
from ._snaphu import get_snaphu_version
from ._version import __version__, __version_tuple__

__all__ = [
    "get_snaphu_version",
    "__version__",
    "__version_tuple__",
]
