# These attributes are defined in _version.py, which is auto-generated by setuptools_scm
# at install time.
__version__: str
__version_tuple__: (
    tuple[int, int, int] | tuple[int, int, int, str] | tuple[int, int, int, str, str]
)
