name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, submodules: true }
      - run: |
          pipx run git-archive-all snaphu-py-${{ github.ref_name }}.zip
          unzip -l snaphu-py-${{ github.ref_name }}.zip
      - run: |
          pipx run git-archive-all snaphu-py-${{ github.ref_name }}.tar.gz
          tar -ztvf snaphu-py-${{ github.ref_name }}.tar.gz
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            snaphu-py-${{ github.ref_name }}.zip
            snaphu-py-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
